<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('meeting_recordings', function (Blueprint $table) {
            $table->id();
            $table->foreignId('room_id')->constrained('meeting_rooms')->cascadeOnDelete();

            // S3 path to the MP4 video file
            $table->string('recording_url', 500)->nullable();

            // Full spoken text — generated by OpenAI Whisper after the meeting ends.
            // LONGTEXT to handle hours-long meetings.
            $table->longText('transcript_text')->nullable();

            // S3 path to the downloadable .txt transcript file
            $table->string('transcript_url', 500)->nullable();

            $table->unsignedBigInteger('file_size_bytes')->nullable();
            $table->unsignedInteger('duration_seconds')->nullable();

            // TRUE while LiveKit recording downloads and Whisper transcript runs.
            // Participants are notified when this flips to false.
            $table->boolean('is_processing')->default(true);

            $table->timestamp('generated_at')->nullable(); // When processing completed
            $table->timestamp('created_at')->useCurrent();

            $table->index(['room_id', 'is_processing']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('meeting_recordings');
    }
};
